
[Network]
#type rpc or channel
Type="rpc"
CAFile="./sdk/gm/gmca.crt"
Cert="./sdk/gm/gmsdk.crt"
Key="./sdk/gm/gmsdk.key"
# if the certificate context is not empty, use it, otherwise read from the certificate file
# multi lines use triple quotes
CAContext=''''''
KeyContext=''''''
CertContext=''''''

[[Network.Connection]]
NodeURL="121.196.203.127:8545"
GroupID=1

[Account]
# only support PEM format for now
KeyFile="./accounts_gm/0x1d29e94559b887e32020074c190522d5354f121b.pem"

[Chain]
ChainID=1
SMCrypto=true

[log]
Path="./"
